name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer
      
      - name: Setup Android SDK
        run: |
          # تحديد المسارات
          export ANDROID_HOME=/home/runner/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          
          # تثبيت أدوات الأندرويد يدوياً عبر buildozer لتكون متاحة
          buildozer android update
          
          # الموافقة على الرخص
          yes | sdkmanager --licenses || true
      
      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer --verbose android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: package
          path: bin/*.apk
