name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          # تثبيت buildozer بنظام sudo ليصبح متاحاً في كل المسارات
          sudo pip3 install --upgrade buildozer
      
      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          # تشغيل البناء بشكل مباشر وبسيط
          buildozer android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: package
          path: bin/*.apk
